# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Trilium PowerShell Module
site_author: "Patrick Morris"
site_description: "Documentation for the Trilium PowerShell Module"
repo_name: TriliumNext-PowerShell-Module
repo_url: https://github.com/ptmorris1/TriliumNext-Powershell-Module

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: green
      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: green
      accent: deep orange
  icon:
    logo: simple/trilium
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - content.code.copy

plugins:
  - offline:
      enabled: true
  - search:
      enabled: true
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#extra_css:
  #- stylesheet/extra.css